window.CONTENT = {
  cs: {
    nav: {
      about: "O mně",
      services: "Služby",
      portfolio: "Portfolio",
      testimonials: "Reference",
      pricing: "Ceník",
      blog: "Blog",
      contact: "Kontakt",
      cta: "Nezávazná konzultace",
    },
    hero: {
      kicker: "Freelance · AI Developer · k dispozici od Q3 2026",
      title: "Stavím AI, která firmě\u00a0šetří\u00a0čas — ne\u00a0tu, co dělá dojem.",
      lead: "Pomáhám týmům vymyslet, kde dává AI reálný business smysl, a pak to postavím. LLM pipelines, RAG, interní nástroje, automatizace.",
      ctaPrimary: "Domluvit hovor",
      ctaSecondary: "Podívat se na práci",
      stats: [
        { k: "6", v: "let v produktu" },
        { k: "40+", v: "LLM integrací" },
        { k: "12", v: "dlouhodobých klientů" },
        { k: "~2\u00a0týdny", v: "typická doba do produkce" },
      ],
      status: "Aktuálně beru 1 nový projekt",
    },
    about: {
      kicker: "O mně",
      title: "Technický konzultant s rukama vývojáře.",
      body: [
        "Šest let píšu produkční software, poslední tři roky převážně s LLM. Pracoval jsem na interních copilotech, RAG systémech nad firemní znalostí, klasifikaci dokumentů a agentních workflow.",
        "Nebavíme se jen o modelech — bavíme se o tom, co tím skutečně vyřešíte. Nejlepší projekty začínají dvěma otázkami: kdo to bude reálně používat a co se změní, když to bude fungovat.",
      ],
      stack: ["Python", "TypeScript", "OpenAI / Anthropic", "pgvector", "LangGraph", "Next.js", "AWS", "Postgres"],
      principles: [
        { t: "Malé, měřitelné kroky", d: "Žádné šestiměsíční dodávky. Ship každé 2 týdny, měříme dopad, korigujeme směr." },
        { t: "Proti AI theatre", d: "Když problém vyřeší SQL query, není to zakázka na agenta. Řeknu vám to dřív, než utratíte rozpočet." },
        { t: "Předám, nezamknu", d: "Dokumentace, tests, onboarding. Aby mohl pokračovat váš tým, i když odjedu." },
      ],
    },
    services: {
      kicker: "Služby",
      title: "Čtyři způsoby, jak můžeme spolupracovat.",
      items: [
        {
          n: "01",
          t: "AI Audit",
          d: "Dvoutýdenní průzkum: kde ve firmě AI přinese hodnotu, kde je to ztráta času. Výstup je priority backlog s odhady.",
          price: "od 45\u00a0000 Kč",
          tags: ["2 týdny", "fixní rozsah"],
        },
        {
          n: "02",
          t: "Prototyp za 2 týdny",
          d: "Postavím funkční prototyp jedné konkrétní use-case. Můžete ho ukázat stakeholderům nebo validovat s uživateli.",
          price: "od 120\u00a0000 Kč",
          tags: ["2 týdny", "fixní cena"],
        },
        {
          n: "03",
          t: "Produkční build",
          d: "Od prototypu do produkce. LLM pipeline, eval sada, monitoring, hand-off vašemu týmu.",
          price: "denní sazba 14\u00a0000 Kč",
          tags: ["6–12 týdnů", "T&M"],
        },
        {
          n: "04",
          t: "Fractional AI Lead",
          d: "1–2 dny týdně jako technický partner. Architektura, code review, mentoring juniorů, jednání s vedením.",
          price: "od 60\u00a0000 Kč / měsíc",
          tags: ["3+ měsíce", "retainer"],
        },
      ],
    },
    portfolio: {
      kicker: "Vybrané projekty",
      title: "Tři případovky, u kterých mohu mluvit otevřeně.",
      items: [
        {
          sector: "Legal Tech",
          t: "Copilot pro revizi smluv",
          d: "RAG nad 12\u00a0000 vzorovými smlouvami + custom evaluator. Zkrátil review ze 40 min na 7 min při stejné kvalitě.",
          metric: "−82\u00a0% času",
          metricLabel: "na revizi dokumentu",
          stack: ["Python", "pgvector", "Claude", "Next.js"],
          img: "Screenshot copilota — split-screen smlouva vs. komentáře",
        },
        {
          sector: "E-commerce",
          t: "Agentní zákaznická podpora",
          d: "First-line agent řeší 61\u00a0% ticketů bez eskalace. Napojeno na Shopify, Zendesk a vnitřní knowledge base.",
          metric: "61\u00a0%",
          metricLabel: "ticketů auto-resolved",
          stack: ["LangGraph", "OpenAI", "Postgres", "AWS"],
          img: "Dashboard s metrikami a sample konverzací",
        },
        {
          sector: "FinTech / compliance",
          t: "Klasifikace rizikových transakcí",
          d: "Hybridní klasifikátor (rules + LLM) pro AML tým. Ruční práce dolů, auditovatelnost nahoru.",
          metric: "3,4×",
          metricLabel: "propustnost analytika",
          stack: ["Python", "DSPy", "Postgres", "dbt"],
          img: "Flow diagram: transakce → rules → LLM review → analyst",
        },
      ],
    },
    testimonials: {
      kicker: "Co říkají klienti",
      items: [
        {
          q: "Jeden z mála lidí, kterého jsem potkal, a který umí říct „tohle AI dělat nemá\". To se v téhle době cení víc než cokoliv jiného.",
          a: "Marek Dvořák",
          r: "CTO, Lexio Legal",
        },
        {
          q: "Prototyp za dva týdny zněl jako marketing. Pak to prostě přišlo a šlo to ukázat boardu. Pokračujeme dál.",
          a: "Eliška Novotná",
          r: "Head of Product, Ordio",
        },
        {
          q: "Technicky nejsilnější konzultant, se kterým jsme pracovali. Nic nezatloukal pod koberec.",
          a: "Tomáš H.",
          r: "VP Engineering (NDA)",
        },
      ],
    },
    pricing: {
      kicker: "Ceník",
      title: "Transparentně, bez hvězdiček.",
      sub: "Ceny jsou bez DPH. U fixních zakázek dostanete scope dokument před podpisem.",
      tiers: [
        { t: "Hodinová konzultace", p: "2\u00a0800 Kč", u: "/ hod", d: "Code review, architektura, second opinion. Min. 2 hod.", cta: "Rezervovat" },
        { t: "Audit", p: "45\u00a0000 Kč", u: "fixní", d: "2 týdny, výstup priority backlog + odhady. Fakturace 50/50.", cta: "Domluvit úvod", featured: true },
        { t: "Denní sazba", p: "14\u00a0000 Kč", u: "/ den", d: "Pro produkční buildy a delší spolupráci. Fakturace měsíčně.", cta: "Napsat" },
      ],
    },
    blog: {
      kicker: "Poznámky",
      title: "Píšu, když mám co říct.",
      items: [
        { tag: "Eval", t: "Proč většina LLM evalů měří jen prompt engineering", d: "Pět vzorů, které jsem viděl selhat v produkci, a co s tím.", date: "04\u00a0/\u00a02026", read: "8 min" },
        { tag: "RAG", t: "Hybrid search není módní doplněk. Ukážu proč.", d: "Konkrétní čísla z projektu na 40M dokumentech.", date: "02\u00a0/\u00a02026", read: "12 min" },
        { tag: "Praxe", t: "Kdy (ne)nasazovat agenta", d: "Rozhodovací framework na dvou stránkách.", date: "12\u00a0/\u00a02025", read: "6 min" },
      ],
    },
    contact: {
      kicker: "Pojďme se bavit",
      title: "Popište projekt — ozvu se do 24 hodin.",
      lead: "Nejlépe funguje, když hned v první zprávě napíšete, co řešíte a v jakém horizontu. Pokud ještě nevíte, napište to taky — často se to vyjasní během úvodního hovoru.",
      form: {
        name: "Jméno",
        company: "Firma",
        email: "Pracovní e-mail",
        budget: "Předpokládaný rozpočet",
        budgetOpts: ["do 100\u00a0000 Kč", "100–500\u00a0000 Kč", "500\u00a0k – 2\u00a0M Kč", "2\u00a0M+ Kč", "zatím nevím"],
        timeline: "Kdy chcete začít",
        timelineOpts: ["Hned", "Do měsíce", "Q3 / Q4 2026", "Zatím průzkum"],
        message: "O čem to má být",
        messagePh: "Krátce o firmě, problému a co by měl být výstup.",
        submit: "Odeslat poptávku",
        sending: "Odesílám…",
        sent: "Odesláno. Ozvu se do 24\u00a0hodin.",
        errors: {
          name: "Napište prosím jméno",
          email: "Zadejte platný e-mail",
          message: "Napište aspoň pár vět o projektu",
        },
      },
      direct: [
        { l: "E-mail", v: "jan.cernousek@post.cz" },
        { l: "Signal", v: "DOPLNIT_TELEFON" },
        { l: "LinkedIn", v: "DOPLNIT_LINKEDIN" },
      ],
    },
    footer: {
      tagline: "Freelance AI developer · Praha & remote",
      colophon: "Navrženo & postaveno vlastnoručně. © 2026.",
    },
  },
  en: {
    nav: {
      about: "About",
      services: "Services",
      portfolio: "Work",
      testimonials: "Words",
      pricing: "Pricing",
      blog: "Notes",
      contact: "Contact",
      cta: "Book a call",
    },
    hero: {
      kicker: "Freelance · AI Developer · available Q3 2026",
      title: "I build AI that saves the team hours — not the kind that looks impressive in a demo.",
      lead: "I help teams figure out where AI actually pays off, then ship it. LLM pipelines, RAG, internal tools, automation.",
      ctaPrimary: "Book a call",
      ctaSecondary: "See the work",
      stats: [
        { k: "6", v: "yrs in production" },
        { k: "40+", v: "LLM integrations" },
        { k: "12", v: "long-term clients" },
        { k: "~2\u00a0weeks", v: "typical time to prod" },
      ],
      status: "Taking 1 new project",
    },
    about: {
      kicker: "About",
      title: "A technical consultant who still writes code.",
      body: [
        "Six years shipping production software, the last three mostly with LLMs. I've worked on internal copilots, RAG over company knowledge, document classification, and agentic workflows.",
        "It's not about the model — it's about what actually gets solved. The best projects start with two questions: who'll really use it, and what changes if it works.",
      ],
      stack: ["Python", "TypeScript", "OpenAI / Anthropic", "pgvector", "LangGraph", "Next.js", "AWS", "Postgres"],
      principles: [
        { t: "Small, measurable steps", d: "No six-month deliveries. Ship every 2 weeks, measure impact, correct course." },
        { t: "Against AI theatre", d: "If SQL solves it, you don't need an agent. I'll tell you before you burn the budget." },
        { t: "Hand off, not lock in", d: "Docs, tests, onboarding. Your team can keep going when I leave." },
      ],
    },
    services: {
      kicker: "Services",
      title: "Four ways we can work together.",
      items: [
        { n: "01", t: "AI Audit", d: "Two-week deep dive: where AI pays off, where it wastes time. Output is a prioritized backlog with estimates.", price: "from €1,800", tags: ["2 weeks", "fixed scope"] },
        { n: "02", t: "2-week Prototype", d: "A working prototype of one specific use case. Show it to stakeholders or validate with users.", price: "from €4,800", tags: ["2 weeks", "fixed price"] },
        { n: "03", t: "Production build", d: "Prototype to production. LLM pipeline, eval suite, monitoring, hand-off to your team.", price: "day rate €560", tags: ["6–12 weeks", "T&M"] },
        { n: "04", t: "Fractional AI Lead", d: "1–2 days a week as your technical partner. Architecture, code review, mentoring, exec conversations.", price: "from €2,400 / month", tags: ["3+ months", "retainer"] },
      ],
    },
    portfolio: {
      kicker: "Selected work",
      title: "Three case studies I can talk about openly.",
      items: [
        { sector: "Legal tech", t: "Contract review copilot", d: "RAG over 12,000 sample contracts + a custom evaluator. Cut review from 40 min to 7 min at equal quality.", metric: "−82%", metricLabel: "review time", stack: ["Python", "pgvector", "Claude", "Next.js"], img: "Copilot screenshot — split-view contract vs. comments" },
        { sector: "E-commerce", t: "Agentic customer support", d: "First-line agent resolves 61% of tickets without escalation. Wired into Shopify, Zendesk, internal KB.", metric: "61%", metricLabel: "tickets auto-resolved", stack: ["LangGraph", "OpenAI", "Postgres", "AWS"], img: "Dashboard with metrics and sample conversations" },
        { sector: "FinTech / compliance", t: "Risky-transaction classifier", d: "Hybrid classifier (rules + LLM) for an AML team. Manual work down, auditability up.", metric: "3.4×", metricLabel: "analyst throughput", stack: ["Python", "DSPy", "Postgres", "dbt"], img: "Flow diagram: txn → rules → LLM review → analyst" },
      ],
    },
    testimonials: {
      kicker: "What clients say",
      items: [
        { q: "One of the few people I've met who'll tell you \u201cAI shouldn't do this.\u201d That's worth more than anything else right now.", a: "Marek Dvořák", r: "CTO, Lexio Legal" },
        { q: "A 2-week prototype sounded like marketing. Then it actually landed and we showed it to the board. We're still going.", a: "Eliška Novotná", r: "Head of Product, Ordio" },
        { q: "Technically the strongest consultant we've worked with. Didn't sweep anything under the rug.", a: "Tomáš H.", r: "VP Engineering (NDA)" },
      ],
    },
    pricing: {
      kicker: "Pricing",
      title: "Plainly, no asterisks.",
      sub: "Prices exclude VAT. For fixed-scope work, you get a scope doc before signing.",
      tiers: [
        { t: "Hourly", p: "€120", u: "/ hr", d: "Code review, architecture, second opinion. 2 hr min.", cta: "Book" },
        { t: "Audit", p: "€1,800", u: "flat", d: "2 weeks, priority backlog + estimates. 50/50 billing.", cta: "Start here", featured: true },
        { t: "Day rate", p: "€560", u: "/ day", d: "For production builds and ongoing work. Billed monthly.", cta: "Get in touch" },
      ],
    },
    blog: {
      kicker: "Notes",
      title: "I write when I've got something to say.",
      items: [
        { tag: "Eval", t: "Why most LLM evals only measure prompt engineering", d: "Five patterns I've seen fail in production and what to do instead.", date: "04\u00a0/\u00a02026", read: "8 min" },
        { tag: "RAG", t: "Hybrid search isn't a fashion item. Here's why.", d: "Concrete numbers from a 40M-doc project.", date: "02\u00a0/\u00a02026", read: "12 min" },
        { tag: "Practice", t: "When (not) to deploy an agent", d: "A two-page decision framework.", date: "12\u00a0/\u00a02025", read: "6 min" },
      ],
    },
    contact: {
      kicker: "Let's talk",
      title: "Describe the project — I'll reply within 24 hours.",
      lead: "It works best when your first message covers what you're solving and on what horizon. If you don't know yet, say that too — we usually figure it out on the intro call.",
      form: {
        name: "Name",
        company: "Company",
        email: "Work email",
        budget: "Estimated budget",
        budgetOpts: ["under €4k", "€4–20k", "€20–80k", "€80k+", "not sure yet"],
        timeline: "When to start",
        timelineOpts: ["ASAP", "Within a month", "Q3 / Q4 2026", "Just exploring"],
        message: "What's it about",
        messagePh: "A few lines about the company, the problem, and what success looks like.",
        submit: "Send inquiry",
        sending: "Sending…",
        sent: "Sent. I'll reply within 24\u00a0hours.",
        errors: { name: "Your name, please", email: "Enter a valid email", message: "A few sentences about the project please" },
      },
      direct: [
        { l: "Email", v: "jan.cernousek@post.cz" },
        { l: "Signal", v: "DOPLNIT_TELEFON" },
        { l: "LinkedIn", v: "DOPLNIT_LINKEDIN" },
      ],
    },
    footer: {
      tagline: "Freelance AI developer · Prague & remote",
      colophon: "Designed & built by hand. © 2026.",
    },
  },
};
